# Generated by Django 3.1 on 2020-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0002_auto_20200902_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(default='investigatie', max_length=100),
        ),
    ]
